[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
games = "HCZ5KdroZ7BQrmkZq1a72t2FVVQuxqVjkR4ZmAvi8CTr"
presale = "uXyqdxGC3btcfYEUt8j4Z7g65jKdxiGKiYjjB5eLand"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "bpf-programs/metaplex_token_metadata_program.so"

[[test.genesis]]
address = "HEvSKofvBgfaexv23kMabbYqxasxU3mQ4ibBMEmJWHny"
program = "bpf-programs/chainlink_store.so"

[[test.genesis]]
address = "cjg3oHmg9uuPsP8D6g29NWvhySJkdYdAo9D25PRbKXJ"
program = "bpf-programs/chainlink_aggregator.so"

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "CH31Xns5z3M1cTAbKW34jcxPPciazARpijcHj9rxtemt"
filename = "bpf-programs/usd_sol_feed_main.json"

[[test.validator.account]]
address = "99B2bTijsU6f1GCT73HmdR7HCFFjGMBcPZY6jZ96ynrR"
filename = "bpf-programs/usd_sol_feed_dev.json"
